clc;
close all;
clear all;

%Definitions of constants
global Definitions;
Definitions=struct('DefaultFiltering', 1, 'LinearInterpolation', 1,...
    'SplineInterpolation', 2, 'ThreeDInterpolation', 3, 'DistanceAlgorithm', 1,...
    'PointAlgorithm', 2, 'ArrowAlgorithm', 3, 'DouglasPeckeur', 4,...
    'CuttingMode', 1, 'SewingMode', 2, 'AllinOne', 1, 'StepbyStep', 2,...
    'OrigDataNotLoaded', 1, 'OrigDataLoaded', 2, 'PathPrepared', 3,...
    'SimulationDone', 4, 'Running', 5, 'Edit', 6, 'Setting', 7, 'ThreeD',...
    0, 'SixD', 1, 'Dots', '.b', 'Graph', '-b');

% Struct with default preperation settings 
global Settings;
Settings=struct('ProgName',{'Test'},...
'CuttingMode',1, 'ConstAngleCutting',180, 'FlyByRadius',1,...
'T_IPO',4, 'StartSphereR',4, 'EndSphereR',4, 'PreFilterMaxDelta',10,...
'PreFilterMaxAngle',50, 'PathSpeed',4, 'ThinOutAngle',180,...
'ThinOutDistance', 1, 'UseCase', Definitions.CuttingMode, 'Prefiltering',...
Definitions.DefaultFiltering, 'ThinOut', Definitions.DistanceAlgorithm,...
'Interpolation', Definitions.LinearInterpolation, 'PreparationMode', Definitions.AllinOne);

% Initialization of the default GUI status
global Status;
Status=struct('State', Definitions.OrigDataNotLoaded, 'PlotDimensions',...
    Definitions.SixD, 'TrackAppearance', Definitions.Dots);

% Initialzation of the last GUI State
global LastState;
LastState=Status.State;

% Start of the GUI
rapid_prototyp_v2;
